image: node:16

pipelines:
  pull-requests:
    '**':
      - step:
          name: Lint & Test
          caches:
            - node # provided by bitbucket to cache node_modules
          script:
            - npm install --include=dev --legacy-peer-deps
            - npm run lint
            - npm run test:unit
  branches:
    master:
      - step:
          name: Build and Deploy
          caches:
            - node
            - nextcache
          script:
            - apt-get update && apt-get -qq install rsync

            - npm ci --cache .npm --prefer-offline --omit=dev --legacy-peer-deps
            - npm run build

            - mkdir deploy-xpm-xapp-prod
            - echo "NEXT_PUBLIC_APP_ENV=prod" > ./deploy-xpm-xapp-prod/.env.local
            - echo "NEXT_PUBLIC_BASE_ORIGIN=https://xapp.xpmarket.com" >> ./deploy-xpm-xapp-prod/.env.local
            - echo "NODE_ENV=production" >> ./deploy-xpm-xapp-prod/.env.local
            - cp -a .next ./deploy-xpm-xapp-prod
            - cp package.json ./deploy-xpm-xapp-prod
            - cp -a node_modules ./deploy-xpm-xapp-prod
            - cp -a public ./deploy-xpm-xapp-prod
            - cp -a next-i18next.config.js ./deploy-xpm-xapp-prod
            - cp -a next.config.js ./deploy-xpm-xapp-prod

            # rsync to a temp directory on remote server
            - rsync -arz --delete $BITBUCKET_CLONE_DIR/deploy-xpm-xapp-prod/ root@195.201.171.86:/var/www/xpm-xapp-temp
            # clear current serving directory, sync from temp directory to serving directory
            - ssh root@195.201.171.86 "rsync -ar --delete /var/www/xpm-xapp-temp/ /var/www/xpm-xapp && rm -r /var/www/xpm-xapp-temp"
            # restart next server
            - ssh root@195.201.171.86 "pm2 restart 2"

definitions:
  caches:
    nextcache: .next/cache
